version: '3'

services:
  kali:
    image: xanonymous/kali
    command: tail -f /dev/null
    volumes:
      - home_data:/root
      - .:/lab
    networks:
      - default
    privileged: true


volumes:
  home_data:

networks:
  default:
