version: "3"

services:
  attacker:
    image: xanonymous/kali
    container_name: seed-attacker
    tty: true
    cap_add:
      - ALL
    privileged: true
    command: tail -f /dev/null
    volumes:
      - ./volumes:/volumes
    network_mode: host

  host:
    image: xanonymous/kali
    container_name: host-10.9.0.5
    command: tail -f /dev/null
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
